Name: titan-tunnel-server
Host: 0.0.0.0
Port: 41004
Redis:
  Host: 127.0.0.1:6379
JwtAuth:
  AccessSecret: 2566e166-c9b1-11f0-9e3b-cfb420234783
  AccessExpire: 86400
Log:
  stat: false
  level: debug   
Pops: 
  - Id: 14bf4178-6160-11f0-a0c5-00163e023040
    Name: "test"
    Area: Korea
    CountryCode: ko
    RpcClient:
      Target: localhost:8080
      Timeout: 30000
    WSURL: "ws://127.0.0.1:41005/ws/node"
    MaxCount: 7000
DefaultArea: Korea
Geo: 
 API: ""
 Key: ""
